### ISSUE TITLE
Add CITATIONS.cff file

### ISSUE THREAD

**Issue by elinscott** [epfl-theos/koopmans#192]
By adding a `CITATIONS.cff` file we can make it very easy to cite `koopmans`.

See https://github.com/citation-file-format/citation-file-format for more details.

This file would look something like this:
```
cff-version: 1.2.0
title: koopmans
version: 1.0.0-beta.4
license: "GPL-2.0-only"
message: >-
  If you use this software, please cite it using the
  metadata from this file.
type: software
authors:
  - given-names: Edward
    family-names: Linscott
    affiliation: École Polytechnique Fédérale de Lausanne
    orcid: 'https://orcid.org/0000-0002-4967-9873'
  - given-names: Riccardo
    family-names: De Gennaro
    affiliation: École Polytechnique Fédérale de Lausanne
    orcid: 'https://orcid.org/0000-0003-1955-0849'
  - given-names: Nicola
    family-names: Colonna
    affiliation: Paul Scherrer Institute
    orcid: 'https://orcid.org/0000-0002-6106-6316'
  - given-names: Nicola
    family-names: Marzari
    email: nicola.marzari@epfl.ch
    affiliation: École Polytechnique Fédérale de Lausanne
    orcid: 'https://orcid.org/0000-0002-9764-0199'
```
